default: &default
  adapter: postgresql
  host: localhost
  password: 123456
  username: jb
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: api_example_dev

test:
  <<: *default
  database: api_example_test

